name: Publish via Dispatch

on: [push, repository_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Echo Hello World
        run: echo 'Hello World'
